repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.12.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ankimorphs/deps/.*|
              ankimorphs/readability_settings_ui.py|
              ankimorphs/adaptiveSubs.py|
              ankimorphs/readability.py|
              ankimorphs/readability_ui.py|
              ankimorphs/preferencesDialog.py|
              ankimorphs/config.py|
              tests/fake_preferences.py|
          )$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: 'ankimorphs/|^tests/'
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
        files: 'ankimorphs/|^tests/'
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        require_serial: true
        types: [ python ]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ankimorphs/deps/.*|
              ankimorphs/readability_settings_ui.py|
              ankimorphs/adaptiveSubs.py|
              ankimorphs/readability.py|
              ankimorphs/readability_ui.py|
              ankimorphs/preferencesDialog.py|
              ankimorphs/config.py|
              tests/fake_preferences.py|
          )$
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
default_language_version:
  python: python3.9
