repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ankimorphs/deps/.*|
              ankimorphs/readability_settings_ui.py|
              ankimorphs/adaptiveSubs.py|
              ankimorphs/readability.py|
              ankimorphs/readability_ui.py|
              ankimorphs/preferencesDialog.py|
              ankimorphs/config.py|
              tests/fake_preferences.py|
          )$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        files: 'ankimorphs/|^tests/'
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        require_serial: true
        types: [ python ]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ankimorphs/deps/.*|
              ankimorphs/ui/.*|
              ankimorphs/old_recalc.py|
              ankimorphs/browser_utils.py|
              ankimorphs/reviewing_utils.py|
              tests/.*|
          )$
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ankimorphs/deps/.*|
              ankimorphs/ui/.*|
              ankimorphs/recalc.py|
              tests/.*|
          )$
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        files: 'ankimorphs/|^tests/'
        exclude: |
          (?x)^(
              ankimorphs/deps/.*|
              ankimorphs/ui/.*|
              ankimorphs/browser_utils.py|
              ankimorphs/mecab_wrapper.py|
              ankimorphs/morph_stats.py|
              ankimorphs/morpheme.py|
              ankimorphs/morphemizer.py|
              ankimorphs/old_recalc.py|
              ankimorphs/reviewing_utils.py|
              ankimorphs/text_utils.py|
              ankimorphs/util_external.py|
              tests/.*|
          )$
#      - id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        pass_filenames: false
#        always_run: true
default_language_version:
  python: python3.9
