name: 'Lock Threads'

on:
  schedule:
    - cron: '21 2 * * *'
  workflow_dispatch:

permissions:
  issues: write

concurrency:
  group: lock-threads

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          issue-inactive-days: '7'
          issue-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
            Please open a new issue for related bugs.
          issue-lock-reason: 'resolved'
          process-only: 'issues'
          log-output: true